# version format
version: 0.1.5.{build}

# branches to build
branches:
  only:
    - master
    - develop

# Allow WMF5 (i.e. PowerShellGallery functionality)
image: WMF 5

#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: 8fzPA9jCuntNmDKjf/RWRvEQuqqsuMNJ7ywZ2hIWnbrETAWc9JtW3PnhEhnRXaIU

build: false

test_script:
  - ps: .\build.ps1 Publish

deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: "GitHub Release"
  auth_token:
    secure: 3GTTXmNgNrCZkv0w/qp8+Be5+f/ApC3bqm5eqSnFcMmb2Muu7KMInEQDJPiU6pj8
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

